export const GET_SUBSCRIPTION_PLANS = 'OCA/Subscription/GET_SUBSCRIPTION_PLANS';
export const GET_SUBSCRIPTION_PLANS_SUCCESS =
    'OCA/Subscription/GET_SUBSCRIPTION_PLANS_SUCCESS';
export const GET_SUBSCRIPTION_PLANS_FAILURE =
    'OCA/Subscription/GET_SUBSCRIPTION_PLANS_FAILURE';

export const PAYMENT_CHECKOUT = 'OCA/Subscription/PAYMENT_CHECKOUT';
export const CANCEL_SUBSCRIPTION = 'OCA/Subscription/CANCEL_SUBSCRIPTION';

export const RESET_REQUESTING = 'OCA/Subscription/RESET_REQUESTING';
