# Generated by Django 2.2.16 on 2020-10-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Notifications'},
        ),
    ]
