# Generated by Django 2.2.12 on 2020-05-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="course_categories", to="course.Category"
            ),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_course",
                        to="course.Course",
                    ),
                ),
            ],
        ),
    ]
