# Generated by Django 2.2.16 on 2020-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_event_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='static/img/course_default.png', upload_to='media/course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subscription_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FREE'), (1, 'PREMIUM')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=256),
            preserve_default=False,
        ),
    ]
