# Generated by Django 2.2.16 on 2020-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200914_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='static/img/course_default.png', upload_to='course/'),
        ),
    ]
