# Generated by Django 2.2.16 on 2020-09-23 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_auto_20200915_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='course',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='minutes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
