# Generated by Django 2.2.16 on 2020-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='is_opened',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
