# Generated by Django 2.2.16 on 2020-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200929_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
