# Generated by Django 2.2.16 on 2020-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200929_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
