# Generated by Django 2.2.16 on 2020-09-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20200929_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_opened',
        ),
    ]
