# Generated by Django 2.2.16 on 2020-10-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20200930_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('pk',), 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'Lesson Progress'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('pk',), 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name_plural': 'Payment Method'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name_plural': 'Recordings'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name_plural': 'Subscription Types'},
        ),
    ]
