# Generated by Django 2.2.16 on 2020-10-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20201001_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.Course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
