# Generated by Django 2.2.16 on 2020-10-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_assignment', to='course.Lesson')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
