# Generated by Django 2.2.16 on 2020-10-15 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0024_auto_20201015_1015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('user', 'course')},
        ),
    ]
