# Generated by Django 2.2.16 on 2020-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20201016_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ManyToManyField(related_name='lesson_assignment', to='course.Lesson'),
        ),
    ]
