# Generated by Django 2.2.16 on 2020-10-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20201016_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifehappensassignment',
            name='loss_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('housingassignment', 'transportation', 'childcare', 'groceryassignment', 'lifehappensassignment', 'restaurantassignment', 'creditcardassignment')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_timelines', to='contenttypes.ContentType'),
        ),
    ]
