# Generated by Django 2.2.16 on 2020-10-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20201016_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardassignment',
            options={'verbose_name_plural': 'Credit Card'},
        ),
        migrations.RenameField(
            model_name='creditcardassignment',
            old_name='min_due',
            new_name='min_payment',
        ),
    ]
