# Generated by Django 2.2.16 on 2020-10-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_auto_20201018_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentprogress',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_progress', to='course.Assignment'),
        ),
    ]
