# Generated by Django 2.2.16 on 2020-10-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_auto_20201021_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('housingassignment', 'transportation', 'childcare', 'groceryassignment', 'lifehappensassignment', 'restaurantassignment', 'creditcardassignment', 'electronic', 'clothing', 'personalcare', 'homefurnishing', 'entertainment')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_timelines', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='EntertainmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entertainment_items', to='course.Entertainment')),
            ],
            options={
                'verbose_name_plural': 'Entertainment Items',
            },
        ),
    ]
