# Generated by Django 2.2.16 on 2020-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_auto_20201021_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
