# Generated by Django 2.2.16 on 2020-11-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20201026_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignment/')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Overview',
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('overview', 'housingassignment', 'transportation', 'childcare', 'groceryassignment', 'lifehappensassignment', 'restaurantassignment', 'creditcardassignment', 'electronic', 'clothing', 'personalcare', 'homefurnishing', 'entertainment')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_timelines', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='course',
            name='initial_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ledger balance'),
        ),
    ]
