# Generated by Django 2.2.16 on 2020-11-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_auto_20201106_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='file',
        ),
    ]
