# Generated by Django 2.2.16 on 2020-12-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_remove_overview_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignment/')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment/')),
            ],
            options={
                'verbose_name_plural': 'Introduction',
            },
        ),
        migrations.RemoveField(
            model_name='clothingitems',
            name='clothing',
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='clothing',
            new_name='giving',
        ),
        migrations.AddField(
            model_name='personalcareitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('introduction', 'housingassignment', 'transportation', 'childcare', 'groceryassignment', 'lifehappensassignment', 'restaurantassignment', 'creditcardassignment', 'electronic', 'personalcare', 'homefurnishing', 'entertainment')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_timelines', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='personalcareitems',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MEN'), (1, 'WOMEN'), (2, 'SOAP_OR_SHAMPOO'), (3, 'MAKE_UP_OR_SKIN_CARE'), (4, 'CLOTHING')], default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsitems',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FAST_FOOD'), (1, 'SIT_DOWN'), (2, 'FANCY')], default=0),
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='ClothingItems',
        ),
    ]
