# Generated by Django 2.2.17 on 2020-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_auto_20201210_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcareitems',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MEN'), (1, 'WOMEN'), (2, 'SOAP_OR_SHAMPOO'), (3, 'MAKE_UP_OR_SKIN_CARE'), (4, 'SHAVING_SUPPLIES'), (5, 'CLOTHING')], default=0),
        ),
    ]
