# Generated by Django 2.2.17 on 2021-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_auto_20201217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsitems',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FAST_FOOD'), (1, 'SIT_DOWN')], default=0),
        ),
    ]
