export const SET_USER_INFO = 'OCA/App/SET_USER_INFO';
export const SET_AUTH_TOKEN = 'OCA/App/SET_AUTH_TOKEN';
export const SET_FACEBOOK_LOGIN = 'OCA/App/SET_FACEBOOK_LOGIN';

export const GET_NOTIFICATIONS_COUNT_SUCCESS =
    'OCA/App/GET_NOTIFICATIONS_COUNT_SUCCESS';

export const RESET_CURRENT_NOTIFICATIONS =
    'OCA/App/RESET_CURRENT_NOTIFICATIONS';

export const LOGOUT = 'OCA/App/LOGOUT';
