export const GET_NOTIFICATIONS = 'OCA/Notifications/GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'OCA/Notifications/GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'OCA/Notifications/GET_NOTIFICATIONS_FAILURE';

export const GET_NOTIFICATIONS_COUNT =
    'OCA/Notifications/GET_NOTIFICATIONS_COUNT';

export const UPDATE_NOTIFICATION =
    'OCA/Notifications/UPDATE_NOTIFICATION';

export const RESET_PAGE = 
    'OCA/Notifications/RESET_PAGE';