export const UPDATE_LESSON_PROGRESS =
    'OCA/LessonDetail/UPDATE_LESSON_PROGRESS';
export const UPDATE_LESSON_PROGRESS_SUCCESS =
    'OCA/LessonDetail/ADD_LESSON_PROGRESS_SUCCESS';

export const RESET = 'OCA/LessonDetail/RESET';
