ICONS = (
    ('accessible-icon', 'accessible-icon'),
    ('american-sign-language-interpreting', 'american-sign-language-interpreting'),
    ('assistive-listening-systems', 'assistive-listening-systems'),
    ('audio-description', 'audio-description'),
    ('blind', 'blind'),
    ('braille', 'braille'),
    ('closed-captioning', 'closed-captioning'),
    ('closed-captioning', 'closed-captioning'),
    ('deaf', 'deaf'),
    ('low-vision', 'low-vision'),
    ('phone-volume', 'phone-volume'),
    ('question-circle', 'question-circle'),
    ('question-circle', 'question-circle'),
    ('sign-language', 'sign-language'),
    ('tty', 'tty'),
    ('universal-access', 'universal-access'),
    ('wheelchair', 'wheelchair'),
    ('angle-double-down', 'angle-double-down'),
    ('angle-double-left', 'angle-double-left'),
    ('angle-double-right', 'angle-double-right'),
    ('angle-double-up', 'angle-double-up'),
    ('angle-down', 'angle-down'),
    ('angle-left', 'angle-left'),
    ('angle-right', 'angle-right'),
    ('angle-up', 'angle-up'),
    ('arrow-alt-circle-down', 'arrow-alt-circle-down'),
    ('arrow-alt-circle-down', 'arrow-alt-circle-down'),
    ('arrow-alt-circle-left', 'arrow-alt-circle-left'),
    ('arrow-alt-circle-left', 'arrow-alt-circle-left'),
    ('arrow-alt-circle-right', 'arrow-alt-circle-right'),
    ('arrow-alt-circle-right', 'arrow-alt-circle-right'),
    ('arrow-alt-circle-up', 'arrow-alt-circle-up'),
    ('arrow-alt-circle-up', 'arrow-alt-circle-up'),
    ('arrow-circle-down', 'arrow-circle-down'),
    ('arrow-circle-left', 'arrow-circle-left'),
    ('arrow-circle-right', 'arrow-circle-right'),
    ('arrow-circle-up', 'arrow-circle-up'),
    ('arrow-down', 'arrow-down'),
    ('arrow-left', 'arrow-left'),
    ('arrow-right', 'arrow-right'),
    ('arrow-up', 'arrow-up'),
    ('arrows-alt', 'arrows-alt'),
    ('arrows-alt-h', 'arrows-alt-h'),
    ('arrows-alt-v', 'arrows-alt-v'),
    ('caret-down', 'caret-down'),
    ('caret-left', 'caret-left'),
    ('caret-right', 'caret-right'),
    ('caret-square-down', 'caret-square-down'),
    ('caret-square-down', 'caret-square-down'), ('caret-square-left', 'caret-square-left'),
    ('caret-square-left', 'caret-square-left'), ('caret-square-right', 'caret-square-right'),
    ('caret-square-right', 'caret-square-right'), ('caret-square-up', 'caret-square-up'),
    ('caret-square-up', 'caret-square-up'), ('caret-up', 'caret-up'), ('cart-arrow-down', 'cart-arrow-down'),
    ('chart-line', 'chart-line'), ('chevron-circle-down', 'chevron-circle-down'),
    ('chevron-circle-left', 'chevron-circle-left'), ('chevron-circle-right', 'chevron-circle-right'),
    ('chevron-circle-up', 'chevron-circle-up'), ('chevron-down', 'chevron-down'), ('chevron-left', 'chevron-left'),
    ('chevron-right', 'chevron-right'), ('chevron-up', 'chevron-up'), ('cloud-download-alt', 'cloud-download-alt'),
    ('cloud-upload-alt', 'cloud-upload-alt'), ('download', 'download'), ('exchange-alt', 'exchange-alt'),
    ('expand-arrows-alt', 'expand-arrows-alt'), ('external-link-alt', 'external-link-alt'),
    ('external-link-square-alt', 'external-link-square-alt'), ('hand-point-down', 'hand-point-down'),
    ('hand-point-down', 'hand-point-down'), ('hand-point-left', 'hand-point-left'),
    ('hand-point-left', 'hand-point-left'), ('hand-point-right', 'hand-point-right'),
    ('hand-point-right', 'hand-point-right'), ('hand-point-up', 'hand-point-up'), ('hand-point-up', 'hand-point-up'),
    ('hand-pointer', 'hand-pointer'), ('hand-pointer', 'hand-pointer'), ('history', 'history'),
    ('level-down-alt', 'level-down-alt'), ('level-up-alt', 'level-up-alt'), ('location-arrow', 'location-arrow'),
    ('long-arrow-alt-down', 'long-arrow-alt-down'), ('long-arrow-alt-left', 'long-arrow-alt-left'),
    ('long-arrow-alt-right', 'long-arrow-alt-right'), ('long-arrow-alt-up', 'long-arrow-alt-up'),
    ('mouse-pointer', 'mouse-pointer'), ('play', 'play'), ('random', 'random'), ('recycle', 'recycle'),
    ('redo', 'redo'), ('redo-alt', 'redo-alt'), ('reply', 'reply'), ('reply-all', 'reply-all'), ('retweet', 'retweet'),
    ('share', 'share'), ('share-square', 'share-square'), ('share-square', 'share-square'),
    ('sign-in-alt', 'sign-in-alt'), ('sign-out-alt', 'sign-out-alt'), ('sort', 'sort'),
    ('sort-alpha-down', 'sort-alpha-down'), ('sort-alpha-up', 'sort-alpha-up'),
    ('sort-amount-down', 'sort-amount-down'), ('sort-amount-up', 'sort-amount-up'), ('sort-down', 'sort-down'),
    ('sort-numeric-down', 'sort-numeric-down'), ('sort-numeric-up', 'sort-numeric-up'), ('sort-up', 'sort-up'),
    ('sync', 'sync'), ('sync-alt', 'sync-alt'), ('text-height', 'text-height'), ('text-width', 'text-width'),
    ('undo', 'undo'), ('undo-alt', 'undo-alt'), ('upload', 'upload'), ('audio-description', 'audio-description'),
    ('backward', 'backward'), ('circle', 'circle'), ('circle', 'circle'), ('closed-captioning', 'closed-captioning'),
    ('closed-captioning', 'closed-captioning'), ('compress', 'compress'), ('eject', 'eject'), ('expand', 'expand'),
    ('expand-arrows-alt', 'expand-arrows-alt'), ('fast-backward', 'fast-backward'), ('fast-forward', 'fast-forward'),
    ('file-audio', 'file-audio'), ('file-audio', 'file-audio'), ('file-video', 'file-video'),
    ('file-video', 'file-video'), ('film', 'film'), ('forward', 'forward'), ('headphones', 'headphones'),
    ('microphone', 'microphone'), ('microphone-slash', 'microphone-slash'), ('music', 'music'), ('pause', 'pause'),
    ('pause-circle', 'pause-circle'), ('pause-circle', 'pause-circle'), ('phone-volume', 'phone-volume'),
    ('play', 'play'), ('play-circle', 'play-circle'), ('play-circle', 'play-circle'), ('podcast', 'podcast'),
    ('random', 'random'), ('redo', 'redo'), ('redo-alt', 'redo-alt'), ('rss', 'rss'), ('rss-square', 'rss-square'),
    ('step-backward', 'step-backward'), ('step-forward', 'step-forward'), ('stop', 'stop'),
    ('stop-circle', 'stop-circle'), ('stop-circle', 'stop-circle'), ('sync', 'sync'), ('sync-alt', 'sync-alt'),
    ('undo', 'undo'), ('undo-alt', 'undo-alt'), ('video', 'video'), ('volume-down', 'volume-down'),
    ('volume-off', 'volume-off'), ('volume-up', 'volume-up'), ('youtube', 'youtube'), ('address-book', 'address-book'),
    ('address-book', 'address-book'), ('address-card', 'address-card'), ('address-card', 'address-card'),
    ('archive', 'archive'), ('balance-scale', 'balance-scale'), ('birthday-cake', 'birthday-cake'), ('book', 'book'),
    ('briefcase', 'briefcase'), ('building', 'building'), ('building', 'building'), ('bullhorn', 'bullhorn'),
    ('bullseye', 'bullseye'), ('calculator', 'calculator'), ('calendar', 'calendar'), ('calendar', 'calendar'),
    ('calendar-alt', 'calendar-alt'), ('calendar-alt', 'calendar-alt'), ('certificate', 'certificate'),
    ('chart-area', 'chart-area'), ('chart-bar', 'chart-bar'), ('chart-bar', 'chart-bar'), ('chart-line', 'chart-line'),
    ('chart-pie', 'chart-pie'), ('clipboard', 'clipboard'), ('clipboard', 'clipboard'), ('coffee', 'coffee'),
    ('columns', 'columns'), ('compass', 'compass'), ('compass', 'compass'), ('copy', 'copy'), ('copy', 'copy'),
    ('copyright', 'copyright'), ('copyright', 'copyright'), ('cut', 'cut'), ('edit', 'edit'), ('edit', 'edit'),
    ('envelope', 'envelope'), ('envelope', 'envelope'), ('envelope-open', 'envelope-open'),
    ('envelope-open', 'envelope-open'), ('envelope-square', 'envelope-square'), ('eraser', 'eraser'), ('fax', 'fax'),
    ('file', 'file'), ('file', 'file'), ('file-alt', 'file-alt'), ('file-alt', 'file-alt'), ('folder', 'folder'),
    ('folder', 'folder'), ('folder-open', 'folder-open'), ('folder-open', 'folder-open'), ('globe', 'globe'),
    ('industry', 'industry'), ('paperclip', 'paperclip'), ('paste', 'paste'), ('pen-square', 'pen-square'),
    ('pencil-alt', 'pencil-alt'), ('percent', 'percent'), ('phone', 'phone'), ('phone-square', 'phone-square'),
    ('phone-volume', 'phone-volume'), ('registered', 'registered'), ('registered', 'registered'), ('save', 'save'),
    ('save', 'save'), ('sitemap', 'sitemap'), ('sticky-note', 'sticky-note'), ('sticky-note', 'sticky-note'),
    ('suitcase', 'suitcase'), ('table', 'table'), ('tag', 'tag'), ('tags', 'tags'), ('tasks', 'tasks'),
    ('thumbtack', 'thumbtack'), ('trademark', 'trademark'), ('chess', 'chess'), ('chess-bishop', 'chess-bishop'),
    ('chess-board', 'chess-board'), ('chess-king', 'chess-king'), ('chess-knight', 'chess-knight'),
    ('chess-pawn', 'chess-pawn'), ('chess-queen', 'chess-queen'), ('chess-rook', 'chess-rook'),
    ('square-full', 'square-full'), ('archive', 'archive'), ('barcode', 'barcode'), ('bath', 'bath'), ('bug', 'bug'),
    ('code', 'code'), ('code-branch', 'code-branch'), ('coffee', 'coffee'), ('file', 'file'), ('file', 'file'),
    ('file-alt', 'file-alt'), ('file-alt', 'file-alt'), ('file-code', 'file-code'), ('file-code', 'file-code'),
    ('filter', 'filter'), ('fire-extinguisher', 'fire-extinguisher'), ('folder', 'folder'), ('folder', 'folder'),
    ('folder-open', 'folder-open'), ('folder-open', 'folder-open'), ('keyboard', 'keyboard'), ('keyboard', 'keyboard'),
    ('microchip', 'microchip'), ('qrcode', 'qrcode'), ('shield-alt', 'shield-alt'), ('sitemap', 'sitemap'),
    ('terminal', 'terminal'), ('user-secret', 'user-secret'), ('window-close', 'window-close'),
    ('window-close', 'window-close'), ('window-maximize', 'window-maximize'), ('window-maximize', 'window-maximize'),
    ('window-minimize', 'window-minimize'), ('window-minimize', 'window-minimize'),
    ('window-restore', 'window-restore'), ('window-restore', 'window-restore'), ('address-book', 'address-book'),
    ('address-book', 'address-book'), ('address-card', 'address-card'), ('address-card', 'address-card'),
    ('american-sign-language-interpreting', 'american-sign-language-interpreting'),
    ('assistive-listening-systems', 'assistive-listening-systems'), ('at', 'at'), ('bell', 'bell'), ('bell', 'bell'),
    ('bell-slash', 'bell-slash'), ('bell-slash', 'bell-slash'), ('bluetooth', 'bluetooth'),
    ('bluetooth-b', 'bluetooth-b'), ('bullhorn', 'bullhorn'), ('comment', 'comment'), ('comment', 'comment'),
    ('comment-alt', 'comment-alt'), ('comment-alt', 'comment-alt'), ('comments', 'comments'), ('comments', 'comments'),
    ('envelope', 'envelope'), ('envelope', 'envelope'), ('envelope-open', 'envelope-open'),
    ('envelope-open', 'envelope-open'), ('envelope-square', 'envelope-square'), ('fax', 'fax'), ('inbox', 'inbox'),
    ('language', 'language'), ('microphone', 'microphone'), ('microphone-slash', 'microphone-slash'),
    ('mobile', 'mobile'), ('mobile-alt', 'mobile-alt'), ('paper-plane', 'paper-plane'), ('paper-plane', 'paper-plane'),
    ('phone', 'phone'), ('phone-square', 'phone-square'), ('phone-volume', 'phone-volume'), ('rss', 'rss'),
    ('rss-square', 'rss-square'), ('tty', 'tty'), ('wifi', 'wifi'), ('desktop', 'desktop'), ('download', 'download'),
    ('hdd', 'hdd'), ('hdd', 'hdd'), ('headphones', 'headphones'), ('keyboard', 'keyboard'), ('keyboard', 'keyboard'),
    ('laptop', 'laptop'), ('microchip', 'microchip'), ('mobile', 'mobile'), ('mobile-alt', 'mobile-alt'),
    ('plug', 'plug'), ('power-off', 'power-off'), ('print', 'print'), ('save', 'save'), ('save', 'save'),
    ('server', 'server'), ('tablet', 'tablet'), ('tablet-alt', 'tablet-alt'), ('tv', 'tv'), ('upload', 'upload'),
    ('bitcoin', 'bitcoin'), ('btc', 'btc'), ('dollar-sign', 'dollar-sign'), ('euro-sign', 'euro-sign'), ('gg', 'gg'),
    ('gg-circle', 'gg-circle'), ('lira-sign', 'lira-sign'), ('money-bill-alt', 'money-bill-alt'),
    ('money-bill-alt', 'money-bill-alt'), ('pound-sign', 'pound-sign'), ('ruble-sign', 'ruble-sign'),
    ('rupee-sign', 'rupee-sign'), ('shekel-sign', 'shekel-sign'), ('won-sign', 'won-sign'), ('yen-sign', 'yen-sign'),
    ('bell', 'bell'), ('bell', 'bell'), ('bell-slash', 'bell-slash'), ('bell-slash', 'bell-slash'),
    ('calendar', 'calendar'), ('calendar', 'calendar'), ('calendar-alt', 'calendar-alt'),
    ('calendar-alt', 'calendar-alt'), ('calendar-check', 'calendar-check'), ('calendar-check', 'calendar-check'),
    ('calendar-minus', 'calendar-minus'), ('calendar-minus', 'calendar-minus'), ('calendar-plus', 'calendar-plus'),
    ('calendar-plus', 'calendar-plus'), ('calendar-times', 'calendar-times'), ('calendar-times', 'calendar-times'),
    ('clock', 'clock'), ('clock', 'clock'), ('hourglass', 'hourglass'), ('hourglass', 'hourglass'),
    ('hourglass-end', 'hourglass-end'), ('hourglass-half', 'hourglass-half'), ('hourglass-start', 'hourglass-start'),
    ('stopwatch', 'stopwatch'), ('adjust', 'adjust'), ('clone', 'clone'), ('clone', 'clone'), ('copy', 'copy'),
    ('copy', 'copy'), ('crop', 'crop'), ('crosshairs', 'crosshairs'), ('cut', 'cut'), ('edit', 'edit'),
    ('edit', 'edit'), ('eraser', 'eraser'), ('eye', 'eye'), ('eye-dropper', 'eye-dropper'), ('eye-slash', 'eye-slash'),
    ('eye-slash', 'eye-slash'), ('object-group', 'object-group'), ('object-group', 'object-group'),
    ('object-ungroup', 'object-ungroup'), ('object-ungroup', 'object-ungroup'), ('paint-brush', 'paint-brush'),
    ('paste', 'paste'), ('pencil-alt', 'pencil-alt'), ('save', 'save'), ('save', 'save'), ('tint', 'tint'),
    ('align-center', 'align-center'), ('align-justify', 'align-justify'), ('align-left', 'align-left'),
    ('align-right', 'align-right'), ('bold', 'bold'), ('clipboard', 'clipboard'), ('clipboard', 'clipboard'),
    ('clone', 'clone'), ('clone', 'clone'), ('columns', 'columns'), ('copy', 'copy'), ('copy', 'copy'), ('cut', 'cut'),
    ('edit', 'edit'), ('edit', 'edit'), ('eraser', 'eraser'), ('file', 'file'), ('file', 'file'),
    ('file-alt', 'file-alt'), ('file-alt', 'file-alt'), ('font', 'font'), ('heading', 'heading'),
    ('i-cursor', 'i-cursor'), ('indent', 'indent'), ('italic', 'italic'), ('link', 'link'), ('list', 'list'),
    ('list-alt', 'list-alt'), ('list-alt', 'list-alt'), ('list-ol', 'list-ol'), ('list-ul', 'list-ul'),
    ('outdent', 'outdent'), ('paper-plane', 'paper-plane'), ('paper-plane', 'paper-plane'), ('paperclip', 'paperclip'),
    ('paragraph', 'paragraph'), ('paste', 'paste'), ('pencil-alt', 'pencil-alt'), ('print', 'print'),
    ('quote-left', 'quote-left'), ('quote-right', 'quote-right'), ('redo', 'redo'), ('redo-alt', 'redo-alt'),
    ('reply', 'reply'), ('reply-all', 'reply-all'), ('share', 'share'), ('strikethrough', 'strikethrough'),
    ('subscript', 'subscript'), ('superscript', 'superscript'), ('sync', 'sync'), ('sync-alt', 'sync-alt'),
    ('table', 'table'), ('tasks', 'tasks'), ('text-height', 'text-height'), ('text-width', 'text-width'), ('th', 'th'),
    ('th-large', 'th-large'), ('th-list', 'th-list'), ('trash', 'trash'), ('trash-alt', 'trash-alt'),
    ('trash-alt', 'trash-alt'), ('underline', 'underline'), ('undo', 'undo'), ('undo-alt', 'undo-alt'),
    ('unlink', 'unlink'), ('archive', 'archive'), ('clone', 'clone'), ('clone', 'clone'), ('copy', 'copy'),
    ('copy', 'copy'), ('cut', 'cut'), ('file', 'file'), ('file', 'file'), ('file-alt', 'file-alt'),
    ('file-alt', 'file-alt'), ('file-archive', 'file-archive'), ('file-archive', 'file-archive'),
    ('file-audio', 'file-audio'), ('file-audio', 'file-audio'), ('file-code', 'file-code'), ('file-code', 'file-code'),
    ('file-excel', 'file-excel'), ('file-excel', 'file-excel'), ('file-image', 'file-image'),
    ('file-image', 'file-image'), ('file-pdf', 'file-pdf'), ('file-pdf', 'file-pdf'),
    ('file-powerpoint', 'file-powerpoint'), ('file-powerpoint', 'file-powerpoint'), ('file-video', 'file-video'),
    ('file-video', 'file-video'), ('file-word', 'file-word'), ('file-word', 'file-word'), ('folder', 'folder'),
    ('folder', 'folder'), ('folder-open', 'folder-open'), ('folder-open', 'folder-open'), ('paste', 'paste'),
    ('save', 'save'), ('save', 'save'), ('sticky-note', 'sticky-note'), ('sticky-note', 'sticky-note'),
    ('genderless', 'genderless'), ('mars', 'mars'), ('mars-double', 'mars-double'), ('mars-stroke', 'mars-stroke'),
    ('mars-stroke-h', 'mars-stroke-h'), ('mars-stroke-v', 'mars-stroke-v'), ('mercury', 'mercury'),
    ('neuter', 'neuter'), ('transgender', 'transgender'), ('transgender-alt', 'transgender-alt'), ('venus', 'venus'),
    ('venus-double', 'venus-double'), ('venus-mars', 'venus-mars'), ('hand-lizard', 'hand-lizard'),
    ('hand-lizard', 'hand-lizard'), ('hand-paper', 'hand-paper'), ('hand-paper', 'hand-paper'),
    ('hand-peace', 'hand-peace'), ('hand-peace', 'hand-peace'), ('hand-point-down', 'hand-point-down'),
    ('hand-point-down', 'hand-point-down'), ('hand-point-left', 'hand-point-left'),
    ('hand-point-left', 'hand-point-left'), ('hand-point-right', 'hand-point-right'),
    ('hand-point-right', 'hand-point-right'), ('hand-point-up', 'hand-point-up'), ('hand-point-up', 'hand-point-up'),
    ('hand-pointer', 'hand-pointer'), ('hand-pointer', 'hand-pointer'), ('hand-rock', 'hand-rock'),
    ('hand-rock', 'hand-rock'), ('hand-scissors', 'hand-scissors'), ('hand-scissors', 'hand-scissors'),
    ('hand-spock', 'hand-spock'), ('hand-spock', 'hand-spock'), ('handshake', 'handshake'), ('handshake', 'handshake'),
    ('thumbs-down', 'thumbs-down'), ('thumbs-down', 'thumbs-down'), ('thumbs-up', 'thumbs-up'),
    ('thumbs-up', 'thumbs-up'), ('accessible-icon', 'accessible-icon'), ('ambulance', 'ambulance'),
    ('h-square', 'h-square'), ('heart', 'heart'), ('heart', 'heart'), ('heartbeat', 'heartbeat'),
    ('hospital', 'hospital'), ('hospital', 'hospital'), ('medkit', 'medkit'), ('plus-square', 'plus-square'),
    ('plus-square', 'plus-square'), ('stethoscope', 'stethoscope'), ('user-md', 'user-md'),
    ('wheelchair', 'wheelchair'), ('adjust', 'adjust'), ('bolt', 'bolt'), ('camera', 'camera'),
    ('camera-retro', 'camera-retro'), ('clone', 'clone'), ('clone', 'clone'), ('compress', 'compress'),
    ('expand', 'expand'), ('eye', 'eye'), ('eye-dropper', 'eye-dropper'), ('eye-slash', 'eye-slash'),
    ('eye-slash', 'eye-slash'), ('file-image', 'file-image'), ('file-image', 'file-image'), ('film', 'film'),
    ('id-badge', 'id-badge'), ('id-badge', 'id-badge'), ('id-card', 'id-card'), ('id-card', 'id-card'),
    ('image', 'image'), ('image', 'image'), ('images', 'images'), ('images', 'images'), ('sliders-h', 'sliders-h'),
    ('tint', 'tint'), ('ban', 'ban'), ('barcode', 'barcode'), ('bars', 'bars'), ('beer', 'beer'), ('bell', 'bell'),
    ('bell', 'bell'), ('bell-slash', 'bell-slash'), ('bell-slash', 'bell-slash'), ('bug', 'bug'),
    ('bullhorn', 'bullhorn'), ('bullseye', 'bullseye'), ('calculator', 'calculator'), ('calendar', 'calendar'),
    ('calendar', 'calendar'), ('calendar-alt', 'calendar-alt'), ('calendar-alt', 'calendar-alt'),
    ('calendar-check', 'calendar-check'), ('calendar-check', 'calendar-check'), ('calendar-minus', 'calendar-minus'),
    ('calendar-minus', 'calendar-minus'), ('calendar-plus', 'calendar-plus'), ('calendar-plus', 'calendar-plus'),
    ('calendar-times', 'calendar-times'), ('calendar-times', 'calendar-times'), ('certificate', 'certificate'),
    ('check', 'check'), ('check-circle', 'check-circle'), ('check-circle', 'check-circle'),
    ('check-square', 'check-square'), ('check-square', 'check-square'), ('circle', 'circle'), ('circle', 'circle'),
    ('clipboard', 'clipboard'), ('clipboard', 'clipboard'), ('clone', 'clone'), ('clone', 'clone'), ('cloud', 'cloud'),
    ('cloud-download-alt', 'cloud-download-alt'), ('cloud-upload-alt', 'cloud-upload-alt'), ('coffee', 'coffee'),
    ('cog', 'cog'), ('cogs', 'cogs'), ('copy', 'copy'), ('copy', 'copy'), ('cut', 'cut'), ('database', 'database'),
    ('dot-circle', 'dot-circle'), ('dot-circle', 'dot-circle'), ('download', 'download'), ('edit', 'edit'),
    ('edit', 'edit'), ('ellipsis-h', 'ellipsis-h'), ('ellipsis-v', 'ellipsis-v'), ('envelope', 'envelope'),
    ('envelope', 'envelope'), ('envelope-open', 'envelope-open'), ('envelope-open', 'envelope-open'),
    ('eraser', 'eraser'), ('exclamation', 'exclamation'), ('exclamation-circle', 'exclamation-circle'),
    ('exclamation-triangle', 'exclamation-triangle'), ('external-link-alt', 'external-link-alt'),
    ('external-link-square-alt', 'external-link-square-alt'), ('eye', 'eye'), ('eye-slash', 'eye-slash'),
    ('eye-slash', 'eye-slash'), ('file', 'file'), ('file', 'file'), ('file-alt', 'file-alt'), ('file-alt', 'file-alt'),
    ('filter', 'filter'), ('flag', 'flag'), ('flag', 'flag'), ('flag-checkered', 'flag-checkered'),
    ('folder', 'folder'), ('folder', 'folder'), ('folder-open', 'folder-open'), ('folder-open', 'folder-open'),
    ('frown', 'frown'), ('frown', 'frown'), ('hashtag', 'hashtag'), ('heart', 'heart'), ('heart', 'heart'),
    ('history', 'history'), ('home', 'home'), ('i-cursor', 'i-cursor'), ('info', 'info'),
    ('info-circle', 'info-circle'), ('language', 'language'), ('magic', 'magic'), ('meh', 'meh'), ('meh', 'meh'),
    ('microphone', 'microphone'), ('microphone-slash', 'microphone-slash'), ('minus', 'minus'),
    ('minus-circle', 'minus-circle'), ('minus-square', 'minus-square'), ('minus-square', 'minus-square'),
    ('paste', 'paste'), ('pencil-alt', 'pencil-alt'), ('plus', 'plus'), ('plus-circle', 'plus-circle'),
    ('plus-square', 'plus-square'), ('plus-square', 'plus-square'), ('qrcode', 'qrcode'), ('question', 'question'),
    ('question-circle', 'question-circle'), ('question-circle', 'question-circle'), ('ambulance', 'ambulance'),
    ('anchor', 'anchor'), ('balance-scale', 'balance-scale'), ('bath', 'bath'), ('bed', 'bed'), ('beer', 'beer'),
    ('bell', 'bell'), ('bell', 'bell'), ('bell-slash', 'bell-slash'), ('bell-slash', 'bell-slash'),
    ('bicycle', 'bicycle'), ('binoculars', 'binoculars'), ('birthday-cake', 'birthday-cake'), ('blind', 'blind'),
    ('bomb', 'bomb'), ('book', 'book'), ('bookmark', 'bookmark'), ('bookmark', 'bookmark'), ('briefcase', 'briefcase'),
    ('building', 'building'), ('building', 'building'), ('car', 'car'), ('coffee', 'coffee'),
    ('crosshairs', 'crosshairs'), ('dollar-sign', 'dollar-sign'), ('eye', 'eye'), ('eye-slash', 'eye-slash'),
    ('eye-slash', 'eye-slash'), ('fighter-jet', 'fighter-jet'), ('fire', 'fire'),
    ('fire-extinguisher', 'fire-extinguisher'), ('flag', 'flag'), ('flag', 'flag'),
    ('flag-checkered', 'flag-checkered'), ('flask', 'flask'), ('gamepad', 'gamepad'), ('gavel', 'gavel'),
    ('gift', 'gift'), ('glass-martini', 'glass-martini'), ('globe', 'globe'), ('graduation-cap', 'graduation-cap'),
    ('h-square', 'h-square'), ('heart', 'heart'), ('heart', 'heart'), ('heartbeat', 'heartbeat'), ('home', 'home'),
    ('hospital', 'hospital'), ('hospital', 'hospital'), ('image', 'image'), ('image', 'image'), ('images', 'images'),
    ('images', 'images'), ('industry', 'industry'), ('info', 'info'), ('info-circle', 'info-circle'), ('key', 'key'),
    ('leaf', 'leaf'), ('lemon', 'lemon'), ('lemon', 'lemon'), ('life-ring', 'life-ring'), ('life-ring', 'life-ring'),
    ('lightbulb', 'lightbulb'), ('lightbulb', 'lightbulb'), ('location-arrow', 'location-arrow'),
    ('low-vision', 'low-vision'), ('magnet', 'magnet'), ('male', 'male'), ('map', 'map'), ('map', 'map'),
    ('map-marker', 'map-marker'), ('map-marker-alt', 'map-marker-alt'), ('map-pin', 'map-pin'),
    ('map-signs', 'map-signs'), ('medkit', 'medkit'), ('money-bill-alt', 'money-bill-alt'),
    ('money-bill-alt', 'money-bill-alt'), ('motorcycle', 'motorcycle'), ('music', 'music'), ('newspaper', 'newspaper'),
    ('newspaper', 'newspaper'), ('paw', 'paw'), ('phone', 'phone'), ('phone-square', 'phone-square'),
    ('phone-volume', 'phone-volume'), ('plane', 'plane'), ('plug', 'plug'), ('plus', 'plus'),
    ('plus-square', 'plus-square'), ('plus-square', 'plus-square'), ('print', 'print'), ('recycle', 'recycle'),
    ('road', 'road'), ('rocket', 'rocket'), ('search', 'search'), ('search-minus', 'search-minus'),
    ('search-plus', 'search-plus'), ('ship', 'ship'), ('shopping-bag', 'shopping-bag'),
    ('shopping-basket', 'shopping-basket'), ('shopping-cart', 'shopping-cart'), ('shower', 'shower'),
    ('street-view', 'street-view'), ('subway', 'subway'), ('suitcase', 'suitcase'), ('tag', 'tag'), ('tags', 'tags'),
    ('taxi', 'taxi'), ('thumbtack', 'thumbtack'), ('ambulance', 'ambulance'), ('anchor', 'anchor'),
    ('archive', 'archive'), ('balance-scale', 'balance-scale'), ('bath', 'bath'), ('bed', 'bed'), ('beer', 'beer'),
    ('bell', 'bell'), ('bell', 'bell'), ('bicycle', 'bicycle'), ('binoculars', 'binoculars'),
    ('birthday-cake', 'birthday-cake'), ('bomb', 'bomb'), ('book', 'book'), ('bookmark', 'bookmark'),
    ('bookmark', 'bookmark'), ('briefcase', 'briefcase'), ('bug', 'bug'), ('building', 'building'),
    ('building', 'building'), ('bullhorn', 'bullhorn'), ('bullseye', 'bullseye'), ('bus', 'bus'),
    ('calculator', 'calculator'), ('calendar', 'calendar'), ('calendar', 'calendar'), ('calendar-alt', 'calendar-alt'),
    ('calendar-alt', 'calendar-alt'), ('camera', 'camera'), ('camera-retro', 'camera-retro'), ('car', 'car'),
    ('clipboard', 'clipboard'), ('clipboard', 'clipboard'), ('cloud', 'cloud'), ('coffee', 'coffee'), ('cog', 'cog'),
    ('cogs', 'cogs'), ('compass', 'compass'), ('compass', 'compass'), ('copy', 'copy'), ('copy', 'copy'),
    ('cube', 'cube'), ('cubes', 'cubes'), ('cut', 'cut'), ('envelope', 'envelope'), ('envelope', 'envelope'),
    ('envelope-open', 'envelope-open'), ('envelope-open', 'envelope-open'), ('eraser', 'eraser'), ('eye', 'eye'),
    ('eye-dropper', 'eye-dropper'), ('fax', 'fax'), ('fighter-jet', 'fighter-jet'), ('file', 'file'), ('file', 'file'),
    ('file-alt', 'file-alt'), ('file-alt', 'file-alt'), ('film', 'film'), ('fire', 'fire'),
    ('fire-extinguisher', 'fire-extinguisher'), ('flag', 'flag'), ('flag', 'flag'),
    ('flag-checkered', 'flag-checkered'), ('flask', 'flask'), ('futbol', 'futbol'), ('futbol', 'futbol'),
    ('gamepad', 'gamepad'), ('gavel', 'gavel'), ('gem', 'gem'), ('gem', 'gem'), ('gift', 'gift'),
    ('glass-martini', 'glass-martini'), ('globe', 'globe'), ('graduation-cap', 'graduation-cap'), ('hdd', 'hdd'),
    ('hdd', 'hdd'), ('headphones', 'headphones'), ('heart', 'heart'), ('heart', 'heart'), ('home', 'home'),
    ('hospital', 'hospital'), ('hospital', 'hospital'), ('hourglass', 'hourglass'), ('hourglass', 'hourglass'),
    ('image', 'image'), ('image', 'image'), ('images', 'images'), ('images', 'images'), ('industry', 'industry'),
    ('key', 'key'), ('keyboard', 'keyboard'), ('keyboard', 'keyboard'), ('laptop', 'laptop'), ('leaf', 'leaf'),
    ('lemon', 'lemon'), ('lemon', 'lemon'), ('life-ring', 'life-ring'), ('life-ring', 'life-ring'),
    ('lightbulb', 'lightbulb'), ('lightbulb', 'lightbulb'), ('lock', 'lock'), ('lock-open', 'lock-open'),
    ('magic', 'magic'), ('magnet', 'magnet'), ('map', 'map'), ('map', 'map'), ('map-marker', 'map-marker'),
    ('map-marker-alt', 'map-marker-alt'), ('amazon-pay', 'amazon-pay'), ('apple-pay', 'apple-pay'), ('bell', 'bell'),
    ('bell', 'bell'), ('bookmark', 'bookmark'), ('bookmark', 'bookmark'), ('bullhorn', 'bullhorn'),
    ('camera', 'camera'), ('camera-retro', 'camera-retro'), ('cart-arrow-down', 'cart-arrow-down'),
    ('cart-plus', 'cart-plus'), ('cc-amazon-pay', 'cc-amazon-pay'), ('cc-amex', 'cc-amex'),
    ('cc-apple-pay', 'cc-apple-pay'), ('cc-diners-club', 'cc-diners-club'), ('cc-discover', 'cc-discover'),
    ('cc-jcb', 'cc-jcb'), ('cc-mastercard', 'cc-mastercard'), ('cc-paypal', 'cc-paypal'), ('cc-stripe', 'cc-stripe'),
    ('cc-visa', 'cc-visa'), ('certificate', 'certificate'), ('credit-card', 'credit-card'),
    ('credit-card', 'credit-card'), ('ethereum', 'ethereum'), ('gem', 'gem'), ('gem', 'gem'), ('gift', 'gift'),
    ('google-wallet', 'google-wallet'), ('handshake', 'handshake'), ('handshake', 'handshake'), ('heart', 'heart'),
    ('heart', 'heart'), ('key', 'key'), ('paypal', 'paypal'), ('shopping-bag', 'shopping-bag'),
    ('shopping-basket', 'shopping-basket'), ('shopping-cart', 'shopping-cart'), ('star', 'star'), ('star', 'star'),
    ('stripe', 'stripe'), ('stripe-s', 'stripe-s'), ('tag', 'tag'), ('tags', 'tags'), ('thumbs-down', 'thumbs-down'),
    ('thumbs-down', 'thumbs-down'), ('thumbs-up', 'thumbs-up'), ('thumbs-up', 'thumbs-up'), ('trophy', 'trophy'),
    ('bookmark', 'bookmark'), ('bookmark', 'bookmark'), ('calendar', 'calendar'), ('calendar', 'calendar'),
    ('certificate', 'certificate'), ('circle', 'circle'), ('circle', 'circle'), ('cloud', 'cloud'),
    ('comment', 'comment'), ('comment', 'comment'), ('file', 'file'), ('file', 'file'), ('folder', 'folder'),
    ('folder', 'folder'), ('heart', 'heart'), ('heart', 'heart'), ('map-marker', 'map-marker'), ('play', 'play'),
    ('square', 'square'), ('square', 'square'), ('star', 'star'), ('star', 'star'), ('asterisk', 'asterisk'),
    ('certificate', 'certificate'), ('circle-notch', 'circle-notch'), ('cog', 'cog'), ('compass', 'compass'),
    ('compass', 'compass'), ('crosshairs', 'crosshairs'), ('life-ring', 'life-ring'), ('life-ring', 'life-ring'),
    ('snowflake', 'snowflake'), ('snowflake', 'snowflake'), ('spinner', 'spinner'), ('sun', 'sun'), ('sun', 'sun'),
    ('sync', 'sync'), ('baseball-ball', 'baseball-ball'), ('basketball-ball', 'basketball-ball'),
    ('bowling-ball', 'bowling-ball'), ('football-ball', 'football-ball'), ('futbol', 'futbol'), ('futbol', 'futbol'),
    ('golf-ball', 'golf-ball'), ('hockey-puck', 'hockey-puck'), ('quidditch', 'quidditch'),
    ('table-tennis', 'table-tennis'), ('volleyball-ball', 'volleyball-ball'), ('ban', 'ban'),
    ('battery-empty', 'battery-empty'), ('battery-full', 'battery-full'), ('battery-half', 'battery-half'),
    ('battery-quarter', 'battery-quarter'), ('battery-three-quarters', 'battery-three-quarters'), ('bell', 'bell'),
    ('bell', 'bell'), ('bell-slash', 'bell-slash'), ('bell-slash', 'bell-slash'), ('calendar', 'calendar'),
    ('calendar', 'calendar'), ('calendar-alt', 'calendar-alt'), ('calendar-alt', 'calendar-alt'),
    ('calendar-check', 'calendar-check'), ('calendar-check', 'calendar-check'), ('calendar-minus', 'calendar-minus'),
    ('calendar-minus', 'calendar-minus'), ('calendar-plus', 'calendar-plus'), ('calendar-plus', 'calendar-plus'),
    ('calendar-times', 'calendar-times'), ('calendar-times', 'calendar-times'), ('cart-arrow-down', 'cart-arrow-down'),
    ('cart-plus', 'cart-plus'), ('exclamation', 'exclamation'), ('exclamation-circle', 'exclamation-circle'),
    ('exclamation-triangle', 'exclamation-triangle'), ('eye', 'eye'), ('eye-slash', 'eye-slash'),
    ('eye-slash', 'eye-slash'), ('file', 'file'), ('file', 'file'), ('file-alt', 'file-alt'), ('file-alt', 'file-alt'),
    ('folder', 'folder'), ('folder', 'folder'), ('folder-open', 'folder-open'), ('folder-open', 'folder-open'),
    ('info', 'info'), ('info-circle', 'info-circle'), ('lock', 'lock'), ('lock-open', 'lock-open'), ('minus', 'minus'),
    ('minus-circle', 'minus-circle'), ('minus-square', 'minus-square'), ('minus-square', 'minus-square'),
    ('plus', 'plus'), ('plus-circle', 'plus-circle'), ('plus-square', 'plus-square'), ('plus-square', 'plus-square'),
    ('question', 'question'), ('question-circle', 'question-circle'), ('question-circle', 'question-circle'),
    ('shield-alt', 'shield-alt'), ('shopping-cart', 'shopping-cart'), ('sign-in-alt', 'sign-in-alt'),
    ('sign-out-alt', 'sign-out-alt'), ('thermometer-empty', 'thermometer-empty'),
    ('thermometer-full', 'thermometer-full'), ('thermometer-half', 'thermometer-half'),
    ('thermometer-quarter', 'thermometer-quarter'), ('thermometer-three-quarters', 'thermometer-three-quarters'),
    ('thumbs-down', 'thumbs-down'), ('thumbs-down', 'thumbs-down'), ('thumbs-up', 'thumbs-up'),
    ('thumbs-up', 'thumbs-up'), ('toggle-off', 'toggle-off'), ('toggle-on', 'toggle-on'), ('unlock', 'unlock'),
    ('unlock-alt', 'unlock-alt'), ('accessible-icon', 'accessible-icon'), ('address-book', 'address-book'),
    ('address-book', 'address-book'), ('address-card', 'address-card'), ('address-card', 'address-card'),
    ('bed', 'bed'), ('blind', 'blind'), ('child', 'child'), ('female', 'female'), ('frown', 'frown'),
    ('frown', 'frown'), ('id-badge', 'id-badge'), ('id-badge', 'id-badge'), ('id-card', 'id-card'),
    ('id-card', 'id-card'), ('male', 'male'), ('meh', 'meh'), ('meh', 'meh'), ('power-off', 'power-off'),
    ('smile', 'smile'), ('smile', 'smile'), ('street-view', 'street-view'), ('user', 'user'), ('user', 'user'),
    ('user-circle', 'user-circle'), ('user-circle', 'user-circle'), ('user-md', 'user-md'), ('user-plus', 'user-plus'),
    ('user-secret', 'user-secret'), ('user-times', 'user-times'), ('users', 'users'), ('wheelchair', 'wheelchair'),
    ('accessible-icon', 'accessible-icon'), ('ambulance', 'ambulance'), ('bicycle', 'bicycle'), ('bus', 'bus'),
    ('car', 'car'), ('fighter-jet', 'fighter-jet'), ('motorcycle', 'motorcycle'), ('paper-plane', 'paper-plane'),
    ('paper-plane', 'paper-plane'), ('plane', 'plane'), ('rocket', 'rocket'), ('ship', 'ship'),
    ('shopping-cart', 'shopping-cart'), ('space-shuttle', 'space-shuttle'), ('subway', 'subway'), ('taxi', 'taxi'),
    ('train', 'train'), ('truck', 'truck'), ('wheelchair', 'wheelchair'), ('archive', 'archive'), ('book', 'book'),
    ('bookmark', 'bookmark'), ('bookmark', 'bookmark'), ('edit', 'edit'), ('edit', 'edit'), ('envelope', 'envelope'),
    ('envelope', 'envelope'), ('envelope-open', 'envelope-open'), ('envelope-open', 'envelope-open'),
    ('eraser', 'eraser'), ('file', 'file'), ('file', 'file'), ('file-alt', 'file-alt'), ('file-alt', 'file-alt'),
    ('folder', 'folder'), ('folder', 'folder'), ('folder-open', 'folder-open'), ('folder-open', 'folder-open'),
    ('keyboard', 'keyboard'), ('keyboard', 'keyboard'), ('newspaper', 'newspaper'), ('newspaper', 'newspaper'),
    ('paper-plane', 'paper-plane'), ('paper-plane', 'paper-plane'), ('paperclip', 'paperclip'),
    ('paragraph', 'paragraph'), ('pen-square', 'pen-square'), ('pencil-alt', 'pencil-alt'),
    ('quote-left', 'quote-left'), ('quote-right', 'quote-right'), ('sticky-note', 'sticky-note'),
    ('sticky-note', 'sticky-note'), ('thumbtack', 'thumbtack'))
