# Generated by Django 2.2.19 on 2021-02-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Stripe id')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('plan_id', models.CharField(blank=True, max_length=64, verbose_name='Plan id')),
                ('plan_name', models.CharField(blank=True, max_length=64, verbose_name='Plan name')),
                ('subscription_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Subscription id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
