export const GET_COURSES = 'OCA/Home/GET_COURSES';
export const GET_COURSES_SUCCESS = 'OCA/Home/GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'OCA/Home/GET_COURSES_FAILURE';

export const GET_CATEGORIES = 'OCA/Home/GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'OCA/Home/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'OCA/Home/GET_CATEGORIES_FAILURE';

export const RESET_PAGE = 'OCA/Home/RESET_PAGE';
