export const REGISTER = 'OCA/Registration/REGISTER';
export const REGISTRATION_SUCCESS = 'OCA/Registration/REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'OCA/Registration/REGISTRATION_FAILURE';

export const VERIFY_USER = 'OCA/Registration/VERIFY_USER';
export const USER_VERIFICATION_SUCCESS =
    'OCA/Registration/USER_VERIFICATION_SUCCESS';
export const USER_VERIFICATION_FAILURE =
    'OCA/Registration/USER_VERIFICATION_FAILURE';

export const VERIFY_PHONE = 'OCA/Registration/VERIFY_PHONE';
export const PHONE_VERIFICATION_SUCCESS =
    'OCA/Registration/PHONE_VERIFICATION_SUCCESS';
export const PHONE_VERIFICATION_FAILURE =
    'OCA/Registration/PHONE_VERIFICATION_FAILURE';

export const RESEND_OTP = 'OCA/Registration/RESEND_OTP';
export const RESEND_OTP_RESET = 'OCA/Registration/RESEND_OTP_RESET';

export const REGISTER_MOBILE_DEVICE = 'OCA/Registartion/REGISTER_MOBILE_DEVICE';
export const REGISTER_MOBILE_DEVICE_SUCCESS =
    'OCA/Registartion/REGISTER_MOBILE_DEVICE_SUCCESS';
export const REGISTER_MOBILE_DEVICE_FAILURE =
    'OCA/Registartion/REGISTER_MOBILE_DEVICE_FAILURE';
