export const GET_CATEGORY_COURSES = 'OCA/CategoryCourses/GET_CATEGORY_COURSES';
export const GET_CATEGORY_COURSES_SUCCESS = 'OCA/CategoryCourses/GET_CATEGORY_COURSES_SUCCESS';
export const GET_CATEGORY_COURSES_FAILURE = 'OCA/CategoryCourses/GET_CATEGORY_COURSES_FAILURE';

export const SEARCH_CATEGORY_COURSES =
    'OCA/CategoryCourses/SEARCH_CATEGORY_COURSES';

export const RESET_PAGE =
    'OCA/CategoryCourses/RESET_PAGE';