export const UPDATE_IMAGE = 'OCA/Profile/UPDATE_IMAGE';

export const UPDATE_FULL_NAME = 'OCA/Profile/UPDATE_FULL_NAME';

export const UPDATE_EMAIL = 'OCA/Profile/UPDATE_EMAIL';

export const UPDATE_PHONE_NUMBER = 'OCA/Profile/UPDATE_PHONE_NUMBER';

export const UPDATE_PASSWORD = 'OCA/Profile/UPDATE_PASSWORD';

export const UPDATE_PROFILE_SUCCESS = 'OCA/Profile/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'OCA/Profile/UPDATE_PROFILE_FAILURE';

export const ASK_QUESTION_REQUEST = 'OCA/Profile/ASK_QUESTION_REQUEST';
export const RESET_QUESTION_REQUEST = 'OCA/Profile/RESET_QUESTION_REQUEST';
