# Generated by Django 2.2.12 on 2020-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_group"),
        ("users", "0002_auto_20200512_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(
                blank=True, related_name="user_group", to="course.Group"
            ),
        ),
    ]
