# Generated by Django 2.2.16 on 2020-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200908_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Admin'), (1, 'Author'), (0, 'Student')], default=0),
        ),
    ]
