# Generated by Django 2.2.16 on 2020-09-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
