# Generated by Django 2.2.16 on 2020-09-29 20:13

import django.contrib.auth.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200926_1207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('active', users.models.OnlyActiveManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
