# Generated by Django 2.2.16 on 2020-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_dial_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
