# Generated by Django 2.2.19 on 2021-02-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_country_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest_class', models.BooleanField(blank=True, default=True, null=True)),
                ('industry', models.IntegerField(blank=True, default=2, null=True)),
                ('download_quality', models.IntegerField(blank=True, default=2, null=True)),
                ('video_quality', models.IntegerField(blank=True, default=2, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
