export const GET_MODULES = 'OCA/CourseDetail/GET_MODULES';
export const GET_MODULES_SUCCESS = 'OCA/CourseDetail/GET_MODULES_SUCCESS';
export const GET_MODULES_FAILURE = 'OCA/CourseDetail/GET_MODULES_FAILURE';

export const ENROLL_COURSE = 'OCA/CourseDetail/ENROLL_COURSE';
export const ENROLL_COURSE_SUCCESS = 'OCA/CourseDetail/ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_FAILURE = 'OCA/CourseDetail/ENROLL_COURSE_FAILURE';

export const RESET_ENROLLED = 'OCA/CourseDetail/RESET_ENROLLED';